deploy: True
tag: scratch
seed: 42

device_id: 'cuda:0'

data:
  epochs: 1
  num_total_steps: 200_000
  context_length: 500
  batch_size: 100
  dtype: "bfloat16"
  hf_name: "monology/pile-uncopyrighted"
  num_workers: 2
  cache_dir: "../../activations/precomputed_activations/precomputed_activations_gemma2/"

llm:
  model_hf_name: "google/gemma-2-2b"
  tokenizer_hf_name: "google/gemma-2-2b"
  dimin: 2304

sae:
  sae_type: 'temporal'
  sae_diff_type: 'topk' # Options: 'relu', 'topk', 'nullify'
  tied_weights: True
  block_id: 1
  exp_factor: 4
  kval_topk: 192
  n_heads: 4
  n_attn_layers: 1
  bottleneck_factor: 1 # bottleneck_factor = dimin / sparsity (kval) = 2304 / 192 = 12
  gamma_reg: 10
  scaling_factor: 0.00666666667 # For gemma2-2b on monology/pile-uncopyrighted
  
optimizer:
  learning_rate: 1e-3
  weight_decay: 1e-4
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 200
  min_lr: 9e-4

eval:
  save_tables: False

log: 
  save_multiple: False
  log_interval: 10
  save_interval: 20000
  wandb_project_name: "TemporalSAE_test"


# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
